os:
  - linux

language: php

php:
  # - '5.6'
  # - '7.0'
  - '7.1'

sudo: false

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
#  - php artisan key:generate
#  - php artisan migrate --seed

script:
  - vendor/bin/phpunit --coverage-text
#  - vendor/bin/phpmd app text codesize design naming unusedcode
#  - vendor/bin/phpunit --testdox --coverage-text tests

notifications:
  email:
    recipients:
      - jgardezi@gmail.com
    on_success: always
    on_failure: always